#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#
# Note 2! The CFLAGS definition is now in the main makefile...

O_TARGET	:= mac-mux.o
obj-$(CONFIG_MACVLAN) := macvlan.o

include $(TOPDIR)/Rules.make
