#!/bin/sh

. /etc/boot
. /etc/network/interfaces
dhcpc=/sbin/udhcpc

start() {
echo "Starting network..."
#---------------- Forward enable--------------------
if [ "$IPV4_FORWARD_ENABLE" = "yes" ] ; then
     echo "Forward ON and iptables FORWARD rule set to ACCEPT"
     echo "1">/proc/sys/net/ipv4/conf/all/forwarding
     echo "2">/proc/sys/net/ipv4/conf/all/arp_announce
     echo "1">/proc/sys/net/ipv4/conf/all/arp_ignore
     iptables -P FORWARD ACCEPT
     else
     iptables -P FORWARD DROP
     echo "1">/proc/sys/net/ipv4/conf/all/arp_announce
     echo "0">/proc/sys/net/ipv4/conf/all/arp_ignore
fi
#------------------ETH0----------------------------------------------
if [ -f /etc/devices/eth0 ]; then
    if [ "$ETH0_ENABLED" = "yes" ]; then
     echo  "   Starting eth0: "
       if [ "$ETH0_IN_BR0" != "yes" ]; then
        echo NoBridge start ETH0
	ip link set eth0 up
	ip addr flush dev eth0
        if [ "$ETH0_USE_DHCP" = "yes" ] && [ "$ETH0_FORCEIP" != "yes" ]; then
           echo "Set IP adress eth0 from DHCP server" 
           $dhcpc -p /var/run/udhcpc-eth0.pid -i eth0 $DHCPOPTS >>/dev/null
        else
           echo "Set IP adress eth0 from local files" 
           ip addr add $ETH0_IPADDR brd + dev eth0
        fi
      fi
    fi
fi
echo ETH0 OK
#------------------ETH1----------------------------------------------
if [ -f /etc/devices/eth1 ]; then
    if [ "$ETH1_ENABLED" = "yes" ]; then
     echo  "   Starting eth1: "
      if [ "$ETH1_IN_BR0" != "yes" ]; then
        echo NoBridge start ETH1
	ip link set eth1 up
	ip addr flush dev eth1
        if [ "$ETH1_USE_DHCP" = "yes" ] && [ "$ETH1_FORCEIP" != "yes" ]; then
           echo "Set IP adress eth1 from DHCP server" 
           $dhcpc -p /var/run/udhcpc-eth1.pid -S -i eth1 $DHCPOPTS >>/dev/null
        else
           echo "Set IP adress eth1 from local files" 
           ip addr add $ETH1_IPADDR brd + dev eth1
        fi
      fi
    fi
fi
echo ETH1 OK
#-------------------------------------VLAN  START---------------------
if [ "$VLAN_START" = "yes" ] && [ "$BRIDGE_START" != "yes" ] ; then
   echo starting VLAN
   /etc/network/vlan
fi
echo OK
}

stop() {

echo "Stop network..."
if [ "$BRIDGE_START" != "yes" ]; then
  #for eth0
  if [ -f /etc/devices/eth0 ]; then
  if [ "$ETH0_ENABLED" = "yes" ]; then
  echo  "   Stopping eth0: "
  ip link set eth0 down
  echo " Ok"
  fi
  fi
  #for eth1
  if [ -f /etc/devices/eth1 ]; then
  if [ "$ETH1_ENABLED" = "yes" ]; then
  echo  "   Stopping eth1: "
  ip link set eth1 down
  echo " Ok"
  fi
  fi
  #for wlan
  if [ -f /etc/devices/wlan0 ]; then
  if [ "$WLAN_ENABLED" = "yes" ]; then
  echo  "   Stopping wlan0: "
  ip link set wlan0 down
  echo " Ok"
  fi
  fi
fi
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
