#!/bin/sh

start() {

echo "At the end we must add special routes. (you know, default gw, etc..)"

/etc/network/routes

}

stop() {
echo OK
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
