#!/bin/sh

start() {
 echo "Starting inetd: "
 /sbin/inetd
 echo " Ok"
}

stop() {
 echo "Stopping inetd: "
 killall inetd
 echo " Ok"
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
