#!/bin/sh

. /etc/boot
. /etc/network/interfaces

modtest=`uname -r`
moddir=/lib/modules/$modtest/kernel/net

start() {
echo  "Starting tc: "
echo Loading modules
if [ "$START_SHAPER" == "yes" ]; then
      mods=`find $moddir/sched -type f`
       for i in $mods; do
          if [ "$i" == "" ];then
           continue;
          fi
          /sbin/insmod $i
       done
    if [ "$BRIDGE_START" != "yes" ]; then
	if [ "$WLAN_ENABLED" == "yes" ]; then
	  tc qdisc add dev wlan0 root esfq perturb 10 hash src quantum 1500
	fi
        if [ "$ETH0_ENABLED" == "yes" ]; then
	  tc qdisc add dev eth0 root esfq perturb 10 hash src quantum 1500
        fi
        if [ "$ETH1_ENABLED" == "yes" ]; then
	  tc qdisc add dev eth1 root esfq perturb 10 hash src quantum 1500
	fi

     else
	if [ "$WLAN_IN_BR0" != "yes" ]; then
	  tc qdisc add dev wlan0 root esfq perturb 10 hash src quantum 1500
	fi
        if [ "$ETH0_IN_BR0" != "yes" ]; then
	  tc qdisc add dev eth0 root esfq perturb 10 hash src quantum 1500
        fi
        if [ "$ETH1_IN_BR0" != "yes" ]; then
	  tc qdisc add dev eth1 root esfq perturb 10 hash src quantum 1500
	fi
	  tc qdisc add dev br0 root esfq perturb 10 hash src quantum 1500
    fi
  /etc/network/tc.start
  echo " Ok"
fi 

}

stop() {
 echo "Stopping tc: "
    tc qdisc del root dev br0 > /dev/null
    tc qdisc del root dev eth0 > /dev/null
    tc qdisc del root dev eth1 > /dev/null
    tc qdisc del root dev wlan0 > /dev/null
    rmmod sch_sfq
    rmmod sch_red
    rmmod sch_ingress
    rmmod sch_esfq
    rmmod sch_csz
 echo " Ok"
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
