#!/bin/sh

. /etc/boot
. /etc/network/interfaces

start() {

NICE="nice --15"

if [ "$L2TP_CALL_START" = "yes" ] ; then
    if [ "$BR0_USE_DHCP" = "yes" ] || [ "$ETH0_USE_DHCP" = "yes" ] || [ "$ETH1_USE_DHCP" = "yes" ] || [ "$WLAN_USE_DHCP" = "yes" ] ; then
        echo "Wait for recive network parametrs from dhcpclient. L2TP start delayed."
        sleep 10
    fi
	sleep 5
    echo "Starting VPN network l2tp..."
    echo > /etc/ppp/connect-errors
    #Disable nat ipsec (SDK)
    echo "0" > /proc/nat_ipsec
    echo "0" > /proc/nat_l2tp
    mkdir -p /var/run/xl2tpd
    $NICE xl2tpd -c /etc/ppp/l2tpd.conf -s /etc/ppp/chap-secrets -p /var/lock/l2tpd.pid &
fi

}


stop() {
echo "Stop VPN network l2tpd..."
    killall xl2tpd
    rm -f /var/lock/l2tpd.pid
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac
