#!/bin/sh

. /etc/boot

start() {

echo -n "Starting lld services:"
if [ "$LLDT_ENABLE" = "yes" ]; then
    lld2d br0
fi

}

stop() {
 echo "Stopping lld "
 killall -9 lld2d > /dev/null
}

case "$1" in
	start)
	    start
	    ;;

	stop)
	    stop
	    ;;

	restart)
	    stop
	    start
	    ;;

	*)
	    echo $"Usage: $0 {start|stop|restart}"
	    exit 1
esac

