#!/bin/sh

#------------------General config mode set-----------------------------
BASE_STATION=YES
VERSION="::Wive-NG-0.2.23::RTL8186-REALTIME::"
FULLREBUILD=YES
CLEANCCACHE=NO
REBUILDTOOLCHAIN=NO
DOS2UNIX=NO
DEBUG=NO
#----------------------------------------------------------------------
#-------------------TOOLCHAIN DIR CONFIG--------------------------------
#root dir of Wive
WIVEROOT=`pwd`
CROSSPATH=$WIVEROOT/toolchain
CROSS_COMPILE=mips-linux-
#--------------------- Packages----------------------------------------
# For all mode
MODULES_ENABLED="YES"
INCLUDE_MENU="YES"
INCLUDE_ARG="YES"
INCLUDE_DROPBEAR="YES"
INCLUDE_NTP_CLIENT="YES"
INCLUDE_PPP_CLIENT="YES"
INCLUDE_OLSR="NO"
INCLUDE_MII="NO"
INCLUDE_ETHTOOL="NO"
#Non sources modules
INCLUDE_CONTROL="YES"
INCLUDE_IAPP="YES"
INCLUDE_AUTH="YES"
INCLUDE_HDC="NO"
# Select packages for AP mode firmware specific
if [ "$BASE_STATION" = "YES" ] ; then
    #debug to console
    INCLUDE_TC="YES"
    INCLUDE_KERNEL_PPTP="YES"
    INCLUDE_PPTP_CLIENT="NO"
    INCLUDE_PPPOE="YES"
    INCLUDE_L2TP_CLIENT="YES"
    INCLUDE_IGMPPROXY="YES"
    INCLUDE_CIFS="YES"
    INCLUDE_DNS="YES"
    INCLUDE_WINS="NO"
    INCLUDE_WPS="NO"
else
    #no console bind
    INCLUDE_TC="YES"
    INCLUDE_KERNEL_PPTP="YES"
    INCLUDE_PPPOE="YES"
    INCLUDE_L2TP_CLIENT="NO"
    INCLUDE_IGMPPROXY="YES"
    INCLUDE_CIFS="YES"
    INCLUDE_DNS="YES"
    INCLUDE_WINS="NO"
    INCLUDE_WPS="NO"
fi
#--------------------- Packages----------------------------------------
