#!/bin/sh

#------------------General config mode set-----------------------------
VERSION="::Wive-NG-0.3.12::RTL8186-REALTIME::"
RTL8196=YES
FULLREBUILD=NO
CLEANCCACHE=NO
REBUILDTOOLCHAIN=NO
DOS2UNIX=NO
DEBUG=NO
#----------------------------------------------------------------------
#-------------------TOOLCHAIN DIR CONFIG--------------------------------
#root dir of Wive
WIVEROOT=`pwd`
CROSSPATH=$WIVEROOT/toolchain
CROSS_COMPILE=mips-linux-
#--------------------- Packages----------------------------------------
# For all mode
MODULES_ENABLED="YES"
INCLUDE_MENU="YES"
INCLUDE_ARG="YES"
INCLUDE_DROPBEAR="YES"
INCLUDE_NTP_CLIENT="YES"
INCLUDE_PPP_CLIENT="YES"
INCLUDE_OLSR="NO"
INCLUDE_MII="NO"
INCLUDE_ETHTOOL="NO"
INCLUDE_ETHERWAKE="YES"
INCLUDE_MCPROBE="YES"
INCLUDE_UDPXY="YES"
#Non sources modules
INCLUDE_CONTROL="YES"
INCLUDE_IAPP="YES"
INCLUDE_AUTH="YES"
INCLUDE_HDC="NO"
#debug to console
INCLUDE_TC="YES"
INCLUDE_KERNEL_PPTP="YES"
INCLUDE_PPTP_CLIENT="NO"
INCLUDE_PPPOE="YES"
INCLUDE_PPPOECD="YES"
INCLUDE_L2TP_CLIENT="YES"
INCLUDE_IGMPPROXY="YES"
INCLUDE_CIFS="YES"
INCLUDE_DNS="YES"
INCLUDE_WINS="NO"
INCLUDE_WPS="NO"
#--------------------- Packages----------------------------------------
