#!/bin/sh

# vconfig set_name_type VLAN_PLUS_VID_NO_PAD
# vconfig add eth0 2
# vconfig add eth0 3
# vconfig add eth0 4
# vconfig add eth0 5
# ifconfig vlan2 192.168.102.100
# ifconfig vlan3 192.168.103.100
# ifconfig vlan4 192.168.104.100
# ifconfig vlan5 192.168.105.100
# ifconfig vlan2 up
# ifconfig vlan3 up
# ifconfig vlan4 up
# ifconfig vlan5 up
